### ISSUE TITLE
Dependency cycle in examples/complete/armada-resources.yaml

### ISSUE THREAD

**Issue by robert-eby** [att-comdev/promenade#47]
There is a dependency cycle in examples/complete/armada-resources.yaml.
Line 147; helm-toolkit has a dependency on itself.
This causes armada to fail.

**Comment by mark-burnett** [comment]
Hey @robert-eby, thanks for reporting this.  The fix happened to be in-flight when you left this and was merged a few hours later: https://review.gerrithub.io/#/c/388312/

**Comment by mark-burnett** [comment]
Closing as this is now resolved, and a bug has been filed with Armada for clearer error messages.
