### ISSUE TITLE
Implement genesis.sh hostname verification

### ISSUE THREAD

**Issue by craiganderson** [att-comdev/promenade#49]
When running genesis.sh script, it became stuck at:

.The connection to the server apiserver.kubernetes.promenade:6443 was refused - did you specify the right host or port?

The problem was that the hostname specified in genesis.sh for the genesis node did not match the hostname of the node the genesis.sh script was being run on.

Suggest that genesis.sh script perform a hostname check up front before it tries to provision containers, if not a set the hostname of the node itself.

**Comment by mark-burnett** [comment]
Hey @craiganderson, thanks for logging this.  I'll try to get it added to our backlog :)

**Comment by mark-burnett** [comment]
Despite this being marked as a partial bug in commit 4f9def0, I think this is fully implemented. @craiganderson Please re-open if you disagree :)
