### ISSUE TITLE
Promenade API can not handle large URL requests for /v1.0/join-scripts

### ISSUE THREAD

**Issue by kskels** [att-comdev/promenade#57]
Promenade API rejects URL calls for very large URL requests.
This is the case when passing large number of labels when getting join scripts.
https://github.com/att-comdev/promenade/blob/master/docs/source/api.rst#v10join-scripts

Logs from Promenade are short - I suspect this is most likely uwsgi buffer size that needs to be increased to something more then default.

Prom log:
invalid request block size: 4204 (max 4096)...skip

**Comment by mark-burnett** [comment]
This is fixed in https://github.com/att-comdev/promenade/commit/249c5195ef2fd1e4d0fb427e0b24d0d783cf37e2
